catalog:
  es-toolkit: 1.43.0
  typescript: 5.9.3
  vitest: npm:@voidzero-dev/vite-plus-test@latest
  vite: npm:@voidzero-dev/vite-plus-core@latest
  vite-plus: latest

catalogs:
  rolldown:
    "@rollipop/rolldown": 0.0.0-beta.3
    "@rollipop/rolldown-pluginutils": 0.0.0-beta.3

nmHoistingLimits: workspaces

nodeLinker: node-modules

npmPublishAccess: public

npmPublishRegistry: "https://registry.npmjs.org"

npmRegistries:
  "https://registry.npmjs.org":
    npmAlwaysAuth: true
