catalog:
  es-toolkit: 1.43.0
  typescript: 5.9.3
  vitest: npm:@voidzero-dev/vite-plus-test@latest
  vite: npm:@voidzero-dev/vite-plus-core@latest
  '@voidzero-dev/vite-plus': latest

catalogs:
  rolldown:
    "@rolldown/pluginutils": 1.0.0-beta.56
    rolldown: 1.0.0-beta.56

nmHoistingLimits: workspaces

nodeLinker: node-modules

npmPublishAccess: public

npmPublishRegistry: "https://registry.npmjs.org"

npmRegistries:
  "https://registry.npmjs.org":
    npmAlwaysAuth: true
npmScopes:
  voidzero-dev:
    npmRegistryServer: https://npm.pkg.github.com
    npmAuthToken: ${VP_TOKEN}
